### ISSUE TITLE
Some errors happend

### ISSUE THREAD

**Issue by hushangh** [NathanJustus/VideoVibrometry_MatlabApp#1]
Sorry man, it's impolite to disturb you. I am a postgraduate from China, and I'm studying for a master's degree. Fortunately, I find your program about PB_Mot_Mag, but I had a problem running your program. Error message: MATLAB:structRefFromNonStruct. If I run that, and it reports "matlab.ui.Figure has no attribute AutoResizeChildren“. I use Matlab2016a software with a laptop Lenovo R7000 2020 with CPU R4600H and Nv Gtx1650. Could you please help me slove this problem or provide more details， thanks very much!

**Comment by NathanJustus** [comment]
Not impolite at all!  

This issue would be fixed by updating your version of Matlab to at least 2019a (the version in which I wrote this tool), although the latest version is preferred.  It appears to be caused because older versions of appdesigner handle the creation/access of UI figure structs differently than newer versions.  Appdesigner doesn't allow access to the problem portion of code, so it is difficult to make backwards-compatible.  

Happy to be of help if you run into any more problems!

**Comment by hushangh** [comment]
Hi, thanks for your timely reply.
After your reminder, I setupd a matlab in V-2019a, as a result I can open the '.mlapp' file exactly, but it remained me that the program established by matlab 2020b and switching it into 2019a compatible (Sorry for my awful Ebglish). But there is something wrong with error message&nbsp;
'''
The function 'im2gray' corresponding to an input parameter of type 'uint8' is not defined.


Error phaseopticflow (line 11)
I = im2double(im2gray(vr.readFrame));


Error VideoVibrometry/ProcessVideoButtonPushed (line 1313)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Vxs(:,:,:,i),Vys(:,:,:,i),ts(:,i)] = phaseOpticFlow(vr,scale,rect,t0,nf,fs,nscales);


Wrong use of MATLAB ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error calculating Button PrivateButtonPushedFcn.
'''
, and I am planning to debug the error.


Best wishes.



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 7, 2022 04:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NathanJustus/VideoVibrometry_MatlabApp] Some errors happend(Issue #1)




 
Not impolite at all!
 
This issue would be fixed by updating your version of Matlab to at least 2019a (the version in which I wrote this tool), although the latest version is preferred.  It appears to be caused because older versions of appdesigner handle the creation/access of UI figure structs differently than newer versions.  Appdesigner doesn't allow access to the problem portion of code, so it is difficult to make backwards-compatible.
 
Happy to be of help if you run into any more problems!

**Comment by NathanJustus** [comment]
I think that might be solved by installing the Image Processing Toolbox to define the im2gray function.  

Alternatively, I vaguely remember a similar bug happening with a certain video type.  What file format are you using for the video?  I will verify that it works with that format and add support if necessary. Also let me know if your video is black/white or rgb.

**Comment by NathanJustus** [comment]
I think I've replicated and fixed the bug, apparently Image Processing Toolbox no longer has the im2gray function since I wrote the app.  I've changed the relevant code section to do the conversion itself without using the toolbox.  Hopefully this fixes the issue and eliminates the need to install the toolbox.  You'll need to replace the phaseOpticFlow.m file with the new one I have just put up.  Also, there shouldn't be a need to do 2019a compatibility mode, whatever is the latest version you have should be fine so long as it is later than ~2019

Please let me know if you run into any more bugs or manage to get it working!  Thanks for your help reporting these bugs

**Comment by hushangh** [comment]
Hello, my friend, I made it work now. Thanks for your help and selfless dedicaton. I will remark your help in my work.&nbsp;


I conclude the problems I met as following:
1. This program maybe edit and build by Matlab2020b, but Matlab2019 can open it and run as well but with some bugs.
2. In the original/old version of codes, the function "im2gray()" is undefined in lower Matlab versions, but you can replay it by "rgb2gray()" in older version of matlab. Absolutly, it has been solved in your latest version of this program.


Thank you very much. I would like to see and learn more about your exllent programmes.


Best wishes!

---Original---
From: ***@***.***&gt;
Date: Fri, Apr 8, 2022 04:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NathanJustus/VideoVibrometry_MatlabApp] Some errors happend(Issue #1)




 
I think I've replicated and fixed the bug, apparently Image Processing Toolbox no longer has the im2gray function since I wrote the app.  I've changed the relevant code section to do the conversion itself without using the toolbox.  Hopefully this fixes the issue and eliminates the need to install the toolbox.
 
Please let me know if you run into any more bugs or manage to get it working!  Thanks for your help reporting these bugs
